# Generated by Django 3.2.6 on 2021-08-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption_1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
