# Generated by Django 3.2.6 on 2021-08-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_image_caption_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption_1',
        ),
        migrations.AddField(
            model_name='image',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
