# Generated by Django 3.2.6 on 2021-08-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210811_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
