# Generated by Django 3.2.6 on 2021-08-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20210811_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption_1',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption_2',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption_3',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption_4',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption_5',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
