# Generated by Django 3.2.6 on 2021-09-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20210823_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
