# Generated by Django 3.2.6 on 2021-09-12 19:21

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='caption',
            name='image',
            field=models.FileField(default='xyz', upload_to=index.models.path_and_rename),
        ),
    ]
