# Generated by Django 3.2.6 on 2021-09-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_caption_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caption',
            name='image',
        ),
    ]
