# Generated by Django 3.2.6 on 2021-09-12 19:42

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_remove_caption_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='caption',
            name='image',
            field=models.FileField(max_length=255, null=True, upload_to=index.models.path_and_rename),
        ),
    ]
